name: Deploy Flask API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Debug SSH connection
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Testing SSH connection to the server..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem deployer@${{ secrets.SERVER_IP }} exit

      - name: Debug SCP
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Testing SCP to copy files to the server..."
          scp -v -o StrictHostKeyChecking=no -i private_key.pem -r * deployer@${{ secrets.SERVER_IP }}:/home/deployer/app/

      - name: Deploy Application on Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Deploying application on the server..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem deployer@${{ secrets.SERVER_IP }} "pkill -f app.py || true; cd /home/deployer/app; nohup python3 app.py > flask_output.log 2>&1 &"

      - name: Clean up private key
        run: rm private_key.pem
