name: Deploy Flask API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy files to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r * deployer@$SERVER_IP:/home/deployer/app/
        ssh -o StrictHostKeyChecking=no -i private_key.pem deployer@$SERVER_IP "pkill -f app.py || true; cd /home/deployer/app; nohup python3 app.py > flask_output.log 2>&1 &"
        rm private_key.pem

    - name: Start Flask application with nohup
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem deployer@$SERVER_IP "
          pkill -f app.py || true;
          cd /home/deployer/app;
          nohup python3 app.py > flask_output.log 2>&1 &
        "
        rm private_key.pem
